///<reference types = "cypress"/>

function randomNumericNumber() {
    var text = "component_";
    var possible = "0123456789";

    for (var i = 0; i < 5; i++)
        text += possible.charAt(Math.floor(Math.random() * possible.length));

    return text;
}

describe('Component Type screen', () => {
    beforeEach('Login as customer', () => {
        cy.loginAsCustomer()
        cy.get('[class="show-collapsible-sidebar collapsible-sidebar border-r border-gray-300 overflow-y-auto"]')
            .then(menuSideBar => {
                cy.wrap(menuSideBar).find('details').eq(1)
                    .contains('p', 'Configurations').click()
                cy.wrap(menuSideBar).find('details').eq(1).find('ul')
                    .contains('a', 'Component Types').click()
            })
    })

    it('Component Type Setup and Delete', () => {
        cy.wait(3000)
        let componentTypeName = randomNumericNumber()
        cy.get('[class="flex justify-between items-center"]')
            .find('button')
            .contains('p', 'Add Component Type').click()
        cy.get('[class="side_bar side_bar shadow-xl overflow-auto w-[402px] px-6 show_side_bar"]')
            .then(addComponentPanel => {
                cy.wrap(addComponentPanel).find('[class="grid grid-cols-1 gap-4"]')
                    .find('input').type(componentTypeName)
                cy.wrap(addComponentPanel).find('[class="mt-4"]')
                    .find('textarea').type(componentTypeName + componentTypeName)
                cy.wrap(addComponentPanel).find('form')
                    .find('[class="flex items-center gap-x-3 py-5"]')
                    .contains('button', 'Save').click()
            })
        cy.get('[class="go2072408551"]', { timeout: 10000 })
            .find('[class="go3958317564"]')
            .should('contain', 'Created Successfully')
        cy.wait(3000)
        cy.get('[class="flex justify-between items-center"]')
            .find('[class="flex items-center gap-x-2"]')
            .find('input').type(componentTypeName, '{enter}')
        cy.wait(3000)
        cy.get('table').find('tbody>tr').eq(0).then(($tr) => {
            cy.wrap($tr).find('td').contains(componentTypeName).click()
        })
        cy.get('[class="flex items-center space-x-3 py-5"]')
            .find('button')
            .contains('Delete').click()
        cy.get('#modal_parent')
            .find('[class="flex justify-end gap-2"]')
            .contains('button', 'Delete').click()
        cy.get('[class="go2072408551"]', { timeout: 10000 })
            .find('[class="go3958317564"]')
            .should('contain', 'Deleted Successfully')
    })

    it('Add Component Type without type name', () => {
        cy.wait(3000)
        let componentTypeName = randomNumericNumber()
        cy.get('[class="flex justify-between items-center"]')
            .find('button')
            .contains('p', 'Add Component Type').click()
        cy.get('[class="side_bar side_bar shadow-xl overflow-auto w-[402px] px-6 show_side_bar"]')
            .then(addComponentPanel => {
                cy.wrap(addComponentPanel).find('[class="mt-4"]')
                    .find('textarea').type(componentTypeName + componentTypeName)
                cy.wrap(addComponentPanel).find('form')
                    .find('[class="flex items-center gap-x-3 py-5"]')
                    .contains('button', 'Save').click()
            })
        cy.get('[class="flex items-center gap-1 mt-1"]')
            .find('P').should('contain', 'Min Value 3 ')
        cy.get('[class="side_bar side_bar shadow-xl overflow-auto w-[402px] px-6 show_side_bar"]')
            .then(addComponentPanel => {
                cy.wrap(addComponentPanel).find('form')
                    .find('[class="flex items-center gap-x-3 py-5"]')
                    .contains('button', 'Cancel').click()
            })
    })

    it('Add component without description', () => {
        cy.wait(3000)
        let componentTypeName = randomNumericNumber()
        cy.get('[class="flex justify-between items-center"]')
            .find('button')
            .contains('p', 'Add Component Type').click()
        cy.get('[class="side_bar side_bar shadow-xl overflow-auto w-[402px] px-6 show_side_bar"]')
            .then(addComponentPanel => {
                cy.wrap(addComponentPanel).find('[class="grid grid-cols-1 gap-4"]')
                    .find('input').type(componentTypeName)
                cy.wrap(addComponentPanel).find('form')
                    .find('[class="flex items-center gap-x-3 py-5"]')
                    .contains('button', 'Save').click()
            })
        cy.get('[class="go2072408551"]', { timeout: 10000 })
            .find('[class="go3958317564"]')
            .should('contain', 'Created Successfully')
        cy.wait(3000)
        cy.get('[class="flex justify-between items-center"]')
            .find('[class="flex items-center gap-x-2"]')
            .find('input').type(componentTypeName, '{enter}')
        cy.wait(3000)
        cy.get('table').find('tbody>tr').eq(0).then(($tr) => {
            cy.wrap($tr).find('td').contains(componentTypeName).click()
        })
        cy.get('[class="flex items-center space-x-3 py-5"]')
            .find('button')
            .contains('Delete').click()
        cy.get('#modal_parent')
            .find('[class="flex justify-end gap-2"]')
            .contains('button', 'Delete').click()
        cy.get('[class="go2072408551"]', { timeout: 10000 })
            .find('[class="go3958317564"]')
            .should('contain', 'Deleted Successfully')
    })

    it('Edit component type', () => {
        cy.wait(3000)
        let componentTypeName = randomNumericNumber()
        cy.get('[class="flex justify-between items-center"]')
            .find('button')
            .contains('p', 'Add Component Type').click()
        cy.get('[class="side_bar side_bar shadow-xl overflow-auto w-[402px] px-6 show_side_bar"]')
            .then(addComponentPanel => {
                cy.wrap(addComponentPanel).find('[class="grid grid-cols-1 gap-4"]')
                    .find('input').type(componentTypeName)
                cy.wrap(addComponentPanel).find('[class="mt-4"]')
                    .find('textarea').type(componentTypeName + componentTypeName)
                cy.wrap(addComponentPanel).find('form')
                    .find('[class="flex items-center gap-x-3 py-5"]')
                    .contains('button', 'Save').click()
            })
        cy.get('[class="go2072408551"]', { timeout: 10000 })
            .find('[class="go3958317564"]')
            .should('contain', 'Created Successfully')
        cy.wait(3000)
        cy.get('[class="flex justify-between items-center"]')
            .find('[class="flex items-center gap-x-2"]')
            .find('input').type(componentTypeName, '{enter}')
        cy.wait(3000)
        cy.get('table').find('tbody>tr').eq(0).then(($tr) => {
            cy.wrap($tr).find('td').contains(componentTypeName).click()
        })
        cy.get('[class="flex items-center space-x-3 py-5"]')
            .find('button')
            .contains('Edit').click()
        cy.get('form')
            .then(form => {
                cy.wrap(form).find('[class="grid grid-cols-1 gap-4"]')
                    .find('input').eq(1).clear().type(componentTypeName+'E')
                cy.wrap(form).find('[class="mt-4"]')
                    .find('textarea').eq(1).clear().type('Edited description')
                cy.wrap(form)
                    .find('[class="flex items-center space-x-3 py-5"]')
                    .contains('button', 'Update').click()
            })

        cy.get('[class="go2072408551"]', { timeout: 10000 })
            .find('[class="go3958317564"]')
            .should('contain', 'Updated Successfully')
    })
})